"""satis_islemi_tablosu_ve_yatirim_durum_alani

Revision ID: 3b49d6461fcb
Revises: 6cbef5d87ecf
Create Date: 2026-03-01 16:05:27.742257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b49d6461fcb'
down_revision = '6cbef5d87ecf'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'satis_islemi' not in inspector.get_table_names():
        op.create_table(
            'satis_islemi',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('yatirim_id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('satis_tarihi', sa.DateTime(), nullable=False),
            sa.Column('satis_fiyati', sa.Numeric(precision=20, scale=6), nullable=False),
            sa.Column('satilan_miktar', sa.Numeric(precision=20, scale=6), nullable=False),
            sa.Column('alis_fiyati_baz', sa.Numeric(precision=20, scale=6), nullable=False),
            sa.Column('fifo_mi', sa.Boolean(), nullable=True),
            sa.Column('komisyon', sa.Numeric(precision=20, scale=6), nullable=True),
            sa.Column('diger_masraf', sa.Numeric(precision=20, scale=6), nullable=True),
            sa.Column('diger_masraf_aciklama', sa.String(length=200), nullable=True),
            sa.Column('stopaj_orani', sa.Numeric(precision=5, scale=2), nullable=True),
            sa.Column('stopaj_tutari', sa.Numeric(precision=20, scale=6), nullable=True),
            sa.Column('stopaj_manuel_mi', sa.Boolean(), nullable=True),
            sa.Column('brut_kar', sa.Numeric(precision=20, scale=6), nullable=True),
            sa.Column('net_kar', sa.Numeric(precision=20, scale=6), nullable=True),
            sa.Column('notlar', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['user.id']),
            sa.ForeignKeyConstraint(['yatirim_id'], ['yatirim.id']),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_satis_islemi_yatirim_id'), 'satis_islemi', ['yatirim_id'], unique=False)
        op.create_index(op.f('ix_satis_islemi_user_id'), 'satis_islemi', ['user_id'], unique=False)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yatirim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('durum', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('alis_komisyon', sa.Numeric(precision=20, scale=6), nullable=True))
        batch_op.create_index(batch_op.f('ix_yatirim_durum'), ['durum'], unique=False)

    op.execute("UPDATE yatirim SET durum='aktif' WHERE durum IS NULL")
    op.execute("UPDATE yatirim SET alis_komisyon=0 WHERE alis_komisyon IS NULL")

    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yatirim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yatirim_durum'))
        batch_op.drop_column('alis_komisyon')
        batch_op.drop_column('durum')

    if 'satis_islemi' in inspector.get_table_names():
        op.drop_index(op.f('ix_satis_islemi_user_id'), table_name='satis_islemi')
        op.drop_index(op.f('ix_satis_islemi_yatirim_id'), table_name='satis_islemi')
        op.drop_table('satis_islemi')

    # ### end Alembic commands ###
