"""stopaj_orani_tablosu_ve_fon_grubu_alani

Revision ID: 6cbef5d87ecf
Revises: 73ea3e635137
Create Date: 2026-03-01 01:42:32.948359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbef5d87ecf'
down_revision = '73ea3e635137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yatirim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fon_grubu', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('fon_tur_kodu', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('semsiye_fon_turu', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fon_unvan_tipi', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kurucu_kodu', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fon_grubu_otomatik', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fon_bilgi_guncelleme', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yatirim', schema=None) as batch_op:
        batch_op.drop_column('fon_bilgi_guncelleme')
        batch_op.drop_column('fon_grubu_otomatik')
        batch_op.drop_column('kurucu_kodu')
        batch_op.drop_column('fon_unvan_tipi')
        batch_op.drop_column('semsiye_fon_turu')
        batch_op.drop_column('fon_tur_kodu')
        batch_op.drop_column('fon_grubu')

    # ### end Alembic commands ###
