"""add indexes for yatirim and fiyat_gecmisi

Revision ID: 73ea3e635137
Revises: 
Create Date: 2026-02-28 21:43:02.378757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73ea3e635137'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiyat_gecmisi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fiyat_gecmisi_tarih'), ['tarih'], unique=False)
        batch_op.create_index(batch_op.f('ix_fiyat_gecmisi_yatirim_id'), ['yatirim_id'], unique=False)

    with op.batch_alter_table('yatirim', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_yatirim_kod'), ['kod'], unique=False)
        batch_op.create_index(batch_op.f('ix_yatirim_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yatirim', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yatirim_user_id'))
        batch_op.drop_index(batch_op.f('ix_yatirim_kod'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('fiyat_gecmisi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fiyat_gecmisi_yatirim_id'))
        batch_op.drop_index(batch_op.f('ix_fiyat_gecmisi_tarih'))

    # ### end Alembic commands ###
